// <auto-generated />
using System;
using BanDongHoSolution.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BanDongHoSolution.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230503083425_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BanDongHoSolution.Data.Models.CHITIETDONHANG", b =>
                {
                    b.Property<int>("MASP")
                        .HasColumnType("int");

                    b.Property<int>("MADH")
                        .HasColumnType("int");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.HasKey("MASP", "MADH");

                    b.HasIndex("MADH");

                    b.ToTable("CHITIETDONHANG", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.CHITIETKM", b =>
                {
                    b.Property<int>("MASP")
                        .HasColumnType("int");

                    b.Property<string>("MAKM")
                        .HasColumnType("char(7)");

                    b.Property<int>("PHANTRAMKM")
                        .HasColumnType("int");

                    b.HasKey("MASP", "MAKM");

                    b.HasIndex("MAKM");

                    b.ToTable("CHITIETKM", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.DONHANG", b =>
                {
                    b.Property<int>("MADH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MADH"));

                    b.Property<string>("DIACHIGIAO")
                        .HasColumnType("ntext");

                    b.Property<int>("MAKH")
                        .HasColumnType("int");

                    b.Property<string>("MOTA")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("NGAYDAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NGAYGIAO")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(12)");

                    b.Property<float?>("TONGTIEN")
                        .HasColumnType("real");

                    b.Property<string>("TRANGTHAI")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MADH");

                    b.HasIndex("MAKH");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.KHACHHANG", b =>
                {
                    b.Property<int>("MAKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MAKH"));

                    b.Property<string>("DIACHI")
                        .HasColumnType("ntext");

                    b.Property<string>("EMAIL")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GIOITINH")
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("MATK")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("TENKH")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MAKH");

                    b.HasIndex("MATK");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.KHUYENMAI", b =>
                {
                    b.Property<string>("MAKM")
                        .HasColumnType("char(7)");

                    b.Property<DateTime?>("NGAYBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NGAYKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TENKM")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MAKM");

                    b.ToTable("KHUYENMAI", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.LOAISANPHAM", b =>
                {
                    b.Property<string>("MALOAISP")
                        .HasColumnType("char(7)");

                    b.Property<string>("TENLOAISP")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MALOAISP");

                    b.ToTable("LOAISANPHAM", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.LOAITK", b =>
                {
                    b.Property<string>("MALOAITK")
                        .HasColumnType("char(7)");

                    b.Property<string>("TENLOAITK")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MALOAITK");

                    b.ToTable("LOAITK", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.SANPHAM", b =>
                {
                    b.Property<int>("MASP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MASP"));

                    b.Property<string>("DANHGIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("DONGIA")
                        .HasColumnType("real");

                    b.Property<string>("HINHLON")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HINHNHO")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MALOAISP")
                        .HasColumnType("char(7)");

                    b.Property<int>("MATH")
                        .HasColumnType("int");

                    b.Property<string>("MOTA")
                        .HasColumnType("ntext");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.Property<string>("TENSP")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MASP");

                    b.HasIndex("MALOAISP");

                    b.HasIndex("MATH");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.TAIKHOAN", b =>
                {
                    b.Property<int>("MATK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MATK"));

                    b.Property<string>("MALOAITK")
                        .HasColumnType("char(7)");

                    b.Property<string>("MATKHAU")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("NGAYDANGKY")
                        .HasColumnType("datetime2");

                    b.Property<string>("TENDN")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TRANGTHAI")
                        .HasColumnType("int");

                    b.HasKey("MATK");

                    b.HasIndex("MALOAITK");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.THUONGHIEU", b =>
                {
                    b.Property<int>("MATH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MATH"));

                    b.Property<string>("HINHTH")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TENTH")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MATH");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.CHITIETDONHANG", b =>
                {
                    b.HasOne("BanDongHoSolution.Data.Models.DONHANG", "DONHANG")
                        .WithMany("CHITIETDONHANGs")
                        .HasForeignKey("MADH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanDongHoSolution.Data.Models.SANPHAM", "SANPHAM")
                        .WithMany("CHITIETDONHANGs")
                        .HasForeignKey("MASP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DONHANG");

                    b.Navigation("SANPHAM");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.CHITIETKM", b =>
                {
                    b.HasOne("BanDongHoSolution.Data.Models.KHUYENMAI", "KHUYENMAI")
                        .WithMany("CHITIETKMs")
                        .HasForeignKey("MAKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanDongHoSolution.Data.Models.SANPHAM", "SANPHAM")
                        .WithMany("CHITIETKMs")
                        .HasForeignKey("MASP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KHUYENMAI");

                    b.Navigation("SANPHAM");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.DONHANG", b =>
                {
                    b.HasOne("BanDongHoSolution.Data.Models.KHACHHANG", "KHACHHANG")
                        .WithMany("DONHANGs")
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KHACHHANG");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.KHACHHANG", b =>
                {
                    b.HasOne("BanDongHoSolution.Data.Models.TAIKHOAN", "TAIKHOAN")
                        .WithMany("KHACHHANGs")
                        .HasForeignKey("MATK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TAIKHOAN");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.SANPHAM", b =>
                {
                    b.HasOne("BanDongHoSolution.Data.Models.LOAISANPHAM", "LOAISANPHAM")
                        .WithMany("SANPHAMs")
                        .HasForeignKey("MALOAISP")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BanDongHoSolution.Data.Models.THUONGHIEU", "THUONGHIEU")
                        .WithMany("SANPHAMs")
                        .HasForeignKey("MATH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LOAISANPHAM");

                    b.Navigation("THUONGHIEU");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.TAIKHOAN", b =>
                {
                    b.HasOne("BanDongHoSolution.Data.Models.LOAITK", "LOAITK")
                        .WithMany("TAIKHOANs")
                        .HasForeignKey("MALOAITK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LOAITK");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.DONHANG", b =>
                {
                    b.Navigation("CHITIETDONHANGs");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.KHACHHANG", b =>
                {
                    b.Navigation("DONHANGs");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.KHUYENMAI", b =>
                {
                    b.Navigation("CHITIETKMs");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.LOAISANPHAM", b =>
                {
                    b.Navigation("SANPHAMs");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.LOAITK", b =>
                {
                    b.Navigation("TAIKHOANs");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.SANPHAM", b =>
                {
                    b.Navigation("CHITIETDONHANGs");

                    b.Navigation("CHITIETKMs");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.TAIKHOAN", b =>
                {
                    b.Navigation("KHACHHANGs");
                });

            modelBuilder.Entity("BanDongHoSolution.Data.Models.THUONGHIEU", b =>
                {
                    b.Navigation("SANPHAMs");
                });
#pragma warning restore 612, 618
        }
    }
}
